---
title: "It’s a new soundtrack: Candidates, Campaigns, and Rally playlists"
format:
  closeread-html
---

:::{.cr-section}

# Background


Music has been constant feature of political life, from social movements to candidate events [7], [1]. Social media brought more ways for candidates to connect, including sharing their playlists with constituents: these songs can provide information about candidates and who they are [3]. As political candidates are increasingly using music at rallies and releasing or revealing playlists, placing their selected songs into this framework can provide clear and concise opportunities to study how they construct their public image, build political brands, and signal values to voters.
Elected representatives can fulfill their duties using different schema: they may see themselves a a dutiful agent, responsible to voters’ needs and demands, as someone who is entrusted with acting according to their understanding of what is best or ‘right’, or something in between. How elected candidates ultimately see their roles can cover this gamut. Jane Mansbridge, puts forward [4] and later refines [5] a model of representation in which we can think of candidates as fulfilling a ‘gyroscope’-type approach. As gyroscopes, candidates are entities in themselves, rotating about their ideals an morals, akin to a brand or a trustee being selected. The role of the campaign is then to help candidates put forward information about themselves in a value- and information-driven manner. Building on Mansbridge’s framework, I anticipate that candidates will use music not only to entertain, but to provide signals about themselves and the current era: political candidates will want to evoke personal traits relative to their candidacy or party.





## Data and Methods
My dataset, from [2], contains 5,930 songs with lyrics gathered from Lyricsmania.com and Genius.com. The original dataset contained 7388 songs (what it termed ‘preexisting songs’), of which 2209 were unique songs. Of these, I focused on relevant events from the dataset: “campaign launch”, “campaign rally”, “campaign stop”, “playlist”, “speech”, and “town hall meeting”. This further narrowed to approximately 2400 songs total, of which 924 were unique. The goal was to focus on where candidates were likely to have chosen their playlists/music for an in-person event. Table 1 shows the number of candidates and songs in each election year covered in the dataset.
For the majority of the analyses, I include one song per campaign to avoid overly skewing the results. This means that while Trump has played ‘God Bless the USA’ by Lee Greenwood approximately 280 times, it only appears once per each of his three campaigns in the analysis. The exception is Figure 1, which does incorporate all plays of songs.
In my analysis, I employ three methods: topic models, natural language processing, and principal component analysis. I aim to provide a clear and replicable framework for studying lyrical music that can be applied beyond the realm of political campaigns. Together, these three methods provide different perspectives on the song lyrics, covering the broad themes within playlists, particular vocabulary and word use, and then a larger picture of the landscape of relative campaigns.
I incorporate Llexicon-based measures, following approaches from [redacted] and [redacted], using Principal Component Analysis to reduce the dimensionality of the corpus. My goals are twofold: provide an interpretable perspective on the candidate music landscape and understand the extent to which candidate playlists are distinct from one another (both generally and relative to the principal components).

To reduce the dimensionality of the data, I employ an iterated approach following Nelson’s computational grounded theory [6]. In this approach, I first consider high loading variables, those which have a strong association with the relevant dimensions. In a second stage, I then use theory to guide selection from these variables, focusing upon expectations about playlists and musics’ roles in candidate campaigns (specifically, linguistic construction (‘you’ vs ‘I’ and social references) and about how songs can be organized, per research from [redacted] (specifically, around emotional and linguistic content, such as sadness, joy, anticipation, explicit language, and cognitive processes).

Preliminary Findings
Across the different campaigns, Trust and Joy are key emotions present. While there is not large-scale research on emotions present in pop songs, [redacted] finds that trust occurs at about 14% of the work in [redacted]. Across all the front runners in the last three US presidential elections, trust comprises about 18% of the emotions present within songs. Additionally, Democratic candidates have more negative emotions than Trump – getting more negative each year, as Figure 2 shows.
I find both cross-party and within-candidate patterns: all candidates increased the use of pro-social language in their playlists, while Democratic candidates increasingly had more negative emotions and more moral language in their songs. Additionally, trust was the most common emotion present in all front-runner candidate playlists. Playlists can send signals about the candidates and how they view their responsibility: as a delegate acting on behalf of the people or as a brand in which voters invest. In the data, Trump, in each of his three campaigns, evidenced more ‘brandidate’-type language in his playlists, with ‘I’ pronounced being used very heavily. In contrast, Democratic candidates tended toward delegate-type language and more inclusive ‘we’ language.
Finally, building upon the themes and emotions present within candidate playlists, I conducted Principal Component Analysis to explore a two-dimensional representation of candidates and playlists. Figure 3 displays the loadings for the variables. Naming the dimensions from left-to-right, the dimension moves from a more linguistic one (pronouns, functions) to a more emotional one (all of the emotion variables). Moving from bottom-to-top, the dimension moves from LIWC’s ‘Analytic’ variable (a more logic-driven framework) to a more socially oriented one (social behavior). Figure 4 shows that most Republican candidates land on the more logical side while Democratic candidates land on the more social side. The range into more emotion-driven songs is also broader on the Democratic side. These trends are also present in song-specific analyses, as shown in Figure 5.
As a candidate’s music choices are now more public and more widely shared, in addition to frequently used at events, understanding the role it play can deepen our understanding of how political candidates see themselves and the roles they hope to ultimately fulfill as elected representatives. This work contributes to our understanding of political communication and speaks to broader cultural themes around music as a tool for connection and communication.

:::

:::{.cr-section}
## References
[1]	R. Costa.	Songs for Campaign Seasons Past and Present - WSJ.	Wall Street Journal, Oct. 2008.	ISSN 0099-9660.	URL https://www.wsj.com/articles/ SB122290103509796055.
[2]	D. Gorzelany-Mostak, N. Graber, and J. Deavill.	Trail Trax, 2024.	URL https:
//db.traxonthetrail.com/.
[3]	W. D. Harpine. “We want yer, McKinley”: Epbdeictic rhetoric in songs from the 1896 presidential campaign. Rhetoric Society Quarterly:, 34(1), 2004. doi: https: //doi.org/10.1080/02773940409391274. URL https://www.tandfonline.com/doi/ abs/10.1080/02773940409391274.
[4]	J. Mansbridge. Rethinking Representation. American Political Science Review, 97(4):515–528, Nov. 2003. ISSN 1537-5943, 0003-0554. doi: 10.1017/ S0003055403000856. URL https://www.cambridge.org/core/journals/ american-political-science-review/article/rethinking-representation/ 608152BA9E3A0D9B0EC01CE4063B9FB3.
[5]	J. Mansbridge.	Clarifying the Concept of Representation.	American Political Science Review, 105(3):621–630, Aug. 2011.	ISSN 1537-5943, 0003-0554.	doi:
10.1017/S0003055411000189. URL https://www.cambridge.org/core/journals/ american-political-science-review/article/clarifying-the-concept-ofrepresentation/8FCAB056D1AA61DAE84D64D409755C12.
[6]	L. K. Nelson. Computational Grounded Theory: A Methodological Framework. Sociological Methods & Research, 49(1):3–42, Feb. 2020. ISSN 0049-1241. doi: 10.1177/0049124117729703. URL https://doi.org/10.1177/0049124117729703.
[7]	B. S. Schoening and E. T. Kasper. Don’t Stop Thinking About the Music: The Politics of Songs and Musicians in Presidential Campaigns. Bloomsbury Publishing PLC, Dec. 2011. ISBN 978-0-7391-7299-5. Google-Books-ID: OUBPAQAAQBAJ.
:::

